language: node_js
node_js:
- '6'
services:
- mongodb
deploy:
  provider: openshift
  user: jonne.pihlanen@gmail.com
  password:
    secure: Q2NnMY52n72EI83+3zNG6cltDHkij4AXoOr4HHcwplGTCNPbGIdY3cSzy6bU3EVW5YU21Wj71SuDqjWtP+53/lvo1q2GVlbuv8Y85vkdvdbKCIwUsg0aOvnGAKHnFlEWPmXdUPU+OV9Ac4ep3qmgcJUkdONa0fRL/8NoPdHLFjBK6o9YfP95Aba2pE4uyLAPA4vpmW+F3t5+HEyZdLPyAsu0c5JT3fkgd82QyAh/OBfVSiz8DylNCyZWCmliTAF2MMVr5u9aNox6jmZ0hgzd7nApD8lcDekKBsbcIA2xoH8EQVJdkRXxyokKA+AnUH3jIGTVIy+YGMG86cz74MyWK1Kim+MniWHVdAcd+Cedgd/3ZFpQDjzm68LdbNXXaJpJ9Mcl2Tzg1ZRbmUbNAJCwY6LI7J4W4u1lG2ae/2dt9gclsyywTJC4VWzYeb6SribFBVrV+cQl0MqEJw85GGtw6GNkRy3MMArp0xgi2avh1tVM6sU0ax0pVlc9jzH7ONsbzTAi2nD+/3vGeGYiyfjvEyjdXPPjgPZK7zUZb+t/Zxjzdk6Xz7IH/fF9k1vEAvz1G+DCtzK3vjHB2OXj9b91fKct+E1jZoTHAKJ04maihzigPmP7BjBnDj5xjozu5amF/cLAf1z8IYmDdRNpd8XlqIl5c7qrstPOzAuATihk65w=
  app: tv-api
  domain: mashupjonne
  on: master
